name: Build Push Deploy@

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
          -u "${{ secrets.raja9949 }}" \
          --password-stdin

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login \
          --username AWS \
          --password-stdin \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t myapp:${{ github.run_number }} .

      - name: Push Image to Docker Hub
        run: |
          docker tag myapp:${{ github.run_number }} \
          ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.run_number }}

          docker push \
          ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.run_number }}

      - name: Push Image to Amazon ECR
        run: |
          docker tag myapp:${{ github.run_number }} \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/myapp:${{ github.run_number }}

          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/myapp:${{ github.run_number }}

      - name: Deploy Container
        run: |
          docker stop myapp || true
          docker rm myapp || true

          docker run -d \
            --name myapp \
            -p 80:80 \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/myapp:${{ github.run_number }}

      - name: Verify Container
        run: |
          docker ps
